kiprotect/klaro

- src/translations.yml
As requested, here is the French translation!
> Added French translation

- src/translations/sv.yml
This creates a Swedish translation (#1)
> Create swedish translation

- README.md
Commented on this in #1, but this PR makes the list of languages complete and explicit, including ones that have open PRs.
(By "complete" I don't mean every language in the EU; that might be a good idea to list out, though.)
> Listing Languages

- src/translations/nl.yml
Added the missing dutch translation for the close button
> Added dutch close translation

- README.md
Storing the answer from https://github.com/KIProtect/klaro/issues/57 so the next guy will find it more easily :)
> Add documentation for klaro.show()

- .gitignore
- .prettierignore
- .prettierrc
- README.md
- dist/config.js
- dist/configs/i18n.js
- dist/index.html
- src/translations/index.js
- src/translations/tr.yml
Hi all,
I've added Turkish language support!
The other update is about the code formatting.
Nowadays, as you know, almost every developer is using **Prettier** to format their codes according to their habits. This can cause various formatting problems when they do some updates on projects that do not use their own Prettier settings. To prevent this, I've added **.prettierrc** and **.prettierignore** files to the project.
I don't know what do you think about this but, I think this could be helpful to keep the same code formatting styles. 
I have also added **yarn.lock** to .gitignore file for yarn users. Maybe this and .prettierrc files could be submitted as another PR.
What do you think?
Thanks,
Abdullah
> Turkish Language Support and Prettier updates

- src/components/apps.js
Changed to fix issue KIProtect#52.
> Changes only saved after pressing save 

- README.md
- src/translations/es.yml
- src/translations/index.js
As per issue #1.
- Created Spanish translation strings
- Updated src/translations/index.js
- Updated README.md
> Add Spanish translation

- README.md
Probably a typo with name of file as package.js updated to package.json
> Changed package.js to package.json

- .gitlab-ci.yml
Add Gitlab CI integration so that contributors can whether or not the tests are passing or what exactly is failing.
Fixes #53.
> Add GitLab CI integration

- src/utils/i18n.js
Added a string type check for window.language
> Fix language toLowerCase error (#93)

- src/components/apps.js
Fixes #92 
Modifying the toggle is the simplest way to solve the issue #92
>  "Toggle all apps" sets all properties to false

- src/translations/de.yml
The deutsch close translation was missing.
> FIX : Add missing DE translation

- src/consent-manager.js
- src/utils/cookies.js
Tries to do the same as #149 in the central utils function `deleteCookie`.
> Matjaeck fix reset consent

- README.md
- dist/index.html
- package-lock.json
- package.json
- webpack.config.js
fixes #81
Filesize of script in README should be updated
> Separate css and js bundle

- src/translations/de.yml
Fixed typos, changed some untypical phrasing
> Update German translations

- src/translations/fr.yml
Hello, I added some missing strings in that file. So, the french version will be ok.
> Add some missing entries breaking FR translation

- dist/config.js
> Task: Enhance docs on deletion of 3rd party cookies

- src/scss/klaro.scss
Adding an default argument to variable declaration allows simple importing of scss file and overriding default variable values with user specific ones.
> Updated SCSS Variables with Default Argument

- src/components/consent-modal.js
Open Privacy Policy link in new window.
> open privacy policy link in new window

- src/translations/da.yml
- src/translations/index.js
Fixes the danish language in #113
> Feature: Add danish translations

- src/translations/no.yml
- src/translations/sv.yml
> Feature: add no and sv buttons translations

- dist/config.js
https://github.com/kiprotect/klaro/issues/223
> Add Matomo requireCookieConsent Feature

- src/translations/ca.yml
This pull request updates the Catalan translation with some missing strings.
> Update Catalan translation with missing strings

- src/components/ide/spec.js
- src/components/services.jsx
I needed that option for myself and have found issue #280 later, so this is my change to hide that slider
> added option to hide "toogle All" Slider

- README.md
I added some precisions on how to use in-app modules and libraries with Klaro.
> Update README with details on modules use with klaro

- releases.json
- releases.yml
> fix-youtube-spelling

- README.md
the link to the docs was redirected properly but the link to js api led to a 404 page
> fix link to js-api

- .prettierrc
- src/components/app.jsx
- src/components/consent-modal.jsx
- src/components/consent-notice.jsx
- src/components/ide/dropdown.jsx
- src/components/purpose-item.jsx
- src/components/service-item.jsx
- src/components/services.jsx
- src/translations/de.yml
- src/translations/en.ref.yml
- src/translations/en.yml
- Fixed .prettierrc for yml
- Fixed accessibility for screenreaders
- Fixed keyboard navigation
> Accessibility-Fixes

- src/translations/hu.yml
I have updated some informal sentences to formal.
> Hungarian language file update

- dist/config.js
- src/components/contextual-consent-notice.jsx
- src/scss/klaro.scss
- src/translations/de.yml
- src/translations/en.ref.yml
- src/translations/en.yml
Change the behaviour of the always button as it has no effect if no klaro cookie is available.
This is a possible solution to fix #417
> Change contextual behaviour for always button

- src/lib.js
See issue https://github.com/klaro-org/klaro-js/issues/536
> Fix #536: Check for optOut state while contextual rendering

- src/consent-manager.js
See https://github.com/klaro-org/klaro-js/issues/480
> fix: csp violation for style attributes
