.gitignore
.npmignore
package.json

Hi,
Thanks a lot for this project and for open sourcing it. We searched for similar libraries recently to use in my company and yours seems really great.
We are working on integrating this on our workflow, and certainly improving the accessibility. My work here starts with being able to install klaro via npm for easier installs.
This code should help you if you want to publish klaro on the public npm registry. What do you think?
related issue: #23

add config for klaro to be installable through npm registry

---

src/translations/fr.yml

There was a small typo in the french translation file.

fix french i18n file spacing issue preventing correct translation

---

package.json
src/consent-manager.js
src/klaro.js
webpack.config.js

I've made some small changes in Klaro to make it work in IE11.
For this I've introduced some new dependencies:
- [Babel-plugin-transform-runtime](https://babeljs.io/docs/en/6.26.3/babel-plugin-transform-runtime): to polyfill ES6 features only where it is needed (this works together witht the babel-runtime dependency)
- [currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript): to stand in for document.currentExecutingScript in IE11 which doesn't have this function
I've also removed node_modules from the webpack babel-loader config because node modules are alreade ES5 and don't need to be transpiled (the code also didn't compile with this included + babel-plugin-transform-runtime) and changed the setter of style to style.cssText for better compatibility.

Made Klaro work in IE11

---

dist/configs/i18n.js

The property name for the Turkish translation is incorrectly set to `en`, overwriting the additional English strings.

Fix example config: Don't overwrite English with Turkish

---

src/translations/de.yml

https://www.duden.de/rechtschreibung/standardmaeszig

Fix typo: standarmäßig → standardmäßig

---

README.md
src/translations/ca.yml
src/translations/index.js

As stated in issue #1, Catalan language translation is provided on this PR.
- Created Catalan translation strings.
- Updated `src/translations/index.js`.
- Updated `README.md`.

Add Catalan language

---

src/consent-manager.js

apps configured as required will load by default, same as optOut apps
declining all apps will no longer disable apps that are configured as required

fix: #86 Required apps not working as expected: can be disabled and not loading by default. 

---

.editorconfig
README.md

Improve the readability of the code blocks in the ReadMe by declaring the languages they are written in.
Also adds an [`.editorconfig`](https://editorconfig.org/) file.

ReadMe: Declare languages for code blocks and fix small word styles

---

.github/ISSUE_TEMPLATE/BugReport.md
.github/ISSUE_TEMPLATE/FeatureRequest.md
.github/ISSUE_TEMPLATE/Question.md

Processing tickets takes up more time when the statements and questions aren't concise.
To help people get their issues resolved faster, I want to give them some help with these issue templates.
Have a look at [MapsCII's template picker](https://github.com/rastapasta/mapscii/issues/new/choose) to see how they work.

Add issue templates for bugs reports, feature requests and questions

---

src/utils/i18n.js

Fixes #110 
The prototypes of globals and default types should not be changed. It may cause side-effects in or from other scripts.

Don't pollute String.prototype with format()

---

LICENSE
dist/config.js
dist/configs/i18n.js
dist/index.html
package.json

The legal entity KIProtect GmbH has replaced the former entity DPKit as a maintainer of "Klaro!".
These changes update links and information about who maintains the software.
Furthermore, the Pull Request adds information about how to receive the list of all copyright holders of this BSD-3-Clause-licensed open source work.

Update maintainer & authors information from DPKit to KIProtect

---

dist/config.js
dist/configs/i18n.js

Resolves #119.
The translations have been moved to individual files in the `/src/translations` folder:
https://github.com/KIProtect/klaro/tree/master/src/translations

Documentation: Correct location of the translations

---

src/scss/klaro.scss

Fixes #153 by adding `z-index: 1` to the X (close) button inside the modal.
If external CSS applies `position: relative` on `h1`s, the heading will make the button inaccessible by overlapping it.

Fix #135 by ensuring the z-index of the close button

---

src/consent-manager.js

This removes a non-operational call to `deleteCookie()` from the `saveConsents()` method. The intention of this code was probably to delete the cookie when no consent was given to any app (correct me if I'm wrong), however it does not work like that.
`this.consents === null` implies that `get defaultConsents()` could return null, which is not the case because even if there aren't any apps configured, `{} !== null`, see 
https://github.com/KIProtect/klaro/blob/29842b836b1b6531baff19be025c36724d6e7a33/src/consent-manager.js#L54
We also do not want to delete the cookie when no consent was given but save the user's choice for his next visits.
I might be missing something but I can't see how `this.consents === null` could ever be true. We also do not perform any null-checks anywhere else.

Remove a non-operational call to deleteCookie().

---

src/consent-manager.js

Rationale for this change is this section from RFC2109
(https://tools.ietf.org/html/rfc2109):
```
Note: For backward compatibility, the separator in the Cookie header
is semi-colon (;) everywhere.  A server should also accept comma (,)
as the separator between cookie-values for future compatibility.
```
Several server-side implementations of Cookie Jars (e.g. rack, the
modular Ruby webserver interface, that is used in a.o. ruby-on-rails)
therefore split the `Cookie` header on `;` and `,`. The unescaped JSON
of the consents contains `,` which causes issues server-side.
This change is able to read cookies written by an older version as
`unescape` will only replace escaped sequences.

Escape/unescape cookie when saving/loading consents

---

src/translations/de.yml

`acceptSelected` is missing from the German translation
Closes #182

Added "acceptSelected" to the German translation

---

dist/index.html

Without this small change the provided documentation is incorrect and the user is not able to get klaro to work!

Add the missing config name as dataset to the klaro script tag

---

dist/index.html

It is quite confusing that the docs at https://klaro.kiprotect.com/ call the config variable `consentConfig`, but then the example config uses `klaroConfig` which is the default, which means that if someone copies the default config and the default JS from the website...
```html
<script defer type="application/javascript" src="config.js"></script>
<script defer data-config="consentConfig" type="application/javascript" src="klaro.js"></script>
```
... nothing works and Klaro doesn't even show a console warning or error.

rename consentConfig to klaroConfig

---

src/components/consent-modal.js
src/components/consent-notice.js
src/scss/klaro.scss

Moved the "accept all" button to the right as accept/submit button are the buttons on the right.
The change make sure most people will use the "accept all" button if enabled.
Closes: #183

Moved "Accept all" to the right

---

examples/klaro-and-webpack/dist/index.html
examples/klaro-and-webpack/src/index.js
src/consent-manager.js

Managing external `<link>` stylesheets via Klaro! also require re-execution similarly to `<script>` includes.
Sample usage:
```
<link rel="stylesheet" type="text/plain" media="all" data-type="text/css" data-href="https://assets.juicer.io/embed.css" data-name="socialmedia">
```

Trigger re-execution for LINK tags as well

---

src/translations/de.yml

I just spotted a typo in the Germany translation.

Fix typo in German translation

---

src/lib.js

The browser console currently displays `GET …/undefined 404 (not found)` for contextual consent notices, since `undefined` will be casted to a string.

Fix a 404 error for contextual consent notices

---

src/scss/modal.scss

The SCSS doesn't compile anymore since v0.7.12, because of this syntax error in modal.scss.

Fix syntax error in modal.scss

---

src/components/consent-notice.jsx

should fix https://github.com/kiprotect/klaro/issues/349
This PR aims to remove the 3 dots in the settings button/link. Its not configureable and even not used in the modal version. Since the "main" text is configureable it makes from my pov no sense to have an extraText variable.
WDYT?

Remove extraText (...) from settings button

---

dist/config.js
src/components/ide/spec.js
src/consent-manager.js
src/stores.js
src/utils/cookies.js

This PR adds a cookiePath parameter to the config to set the cookie path of the consent cookie.
This would fix #63 since the cookieDomain is already configurable

Add a config parameter for the cookie path of the consent cookie

---

src/consent-manager.js

That way you could change the type attribute of a style tag from text/plain to text/css. The latest Chrome, Firefox and Opera toggle the styles fine with that on a Mac. The text/plain styles are initially not executed and they are reset after the service is disabled. Mobile browsers and IE/Edge have to be checked.
```
<style type="text/plain" data-type="text/css" data-name="styling">
h1 {
color: #f00;
}
</style>
```
A client likes to enable/disable external fonts provided by fonts.com with a counting tracker and this could work inline without referring an external css file.
```
<style type="text/plain" data-type="text/css" data-name="styling">
@import url("http://fast.fonts.net/t/1.css?apiType=css&projectid=XXXXXXXXX");
@font-face{
font-family:"Brandon Text W04"; …
```

Allow the type to be changed for other tags

---

src/translations/pl.yml

Makes the Polish translation actually make sense by removing overly immature stuff, correcting grammar mistakes and changing the context of some translations (for example, "Blisko" in Polish doesn't stand for "Close" as in closing a cookie banner, but as in being close to someone/something 😛).

Improve Polish translations

---

src/scss/switch.scss

`color` is not declared elsewhere as variable.

Fix unidentified variable

---

src/scss/klaro.scss

When using sass@1.77.7, some warnings occur when running `npm run css`. More info at Sass: [Breaking Change: Mixed Declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/).
The fix is to move the calls to mixins in the code and the warnings are not displayed anymore.

Fix use of declarations after nested rules (deprecated since Sass 1.77.7)

---

src/components/consent-notice.jsx

Klaro loses its autofocus when the main page, into which Klaro has been loaded, focuses on one of its own elements. Accepting or rejecting cookie consent should be first thing on focus (if the  `autofocus` is set to `true` in config). This is an accessibility issue for keyboard navigation.
To test this issue in action:
- Set `autofocus` to `true` in config.js located in `klaro-js/dist/config.js`
- In the `simple.html` located in `klaro-js/dist/examples/simple.html`, add an input element in the body with an id, for example `<input id="autofocus-test"></input>`, then create a new script tag like so `<script>document.getElementById("autofocus-test").focus()</script>`
- Opening the example page `simple.html` will result the focus going to the input box instead of klaro's cookie notice.

Fixed an issue with Klaro autofocus

---

README.md

Source: https://bundlephobia.com/package/klaro@0.7.18

Update bundle size in README
